name: SimpleBuffedMobs
version: '${version}'
main: me.pavelsgarklavs.buffedmobs.SimpleBuffedMobs
api-version: 1.17
authors: [ Dev_Pavels ]
description: Mobs but they are buffed!
website: pavelsgarklavs.me
